package org.iz.navigation.data

import org.json.JSONObject

/** Fixed synthetic payload using the pre-rename v5 schema; never generated by BackupJson.encode.
 * The old format literal is retained only to exercise compatibility with existing user backups.
 */
internal object LegacyBackupFixture {
    fun manifest() = JSONObject("""
        {
          "format":"com.atay.iz.backup", "version":5, "exportedAt":6000,
          "journeys":[{"id":"run","title":"Saved run","transport":"RUN","status":"CONFIRMED","startedAt":1000,"endedAt":5000,"expiresAt":null,"note":"Private route","interrupted":false,"stepCount":42}],
          "points":[{"id":"point","journeyId":"run","latitude":41.0,"longitude":29.0,"recordedAt":2000,"accuracy":5.0,"speed":2.0,"altitude":10.0,"breakBefore":true}],
          "places":[{"id":"place","name":"Old place","latitude":41.0,"longitude":29.0,"googlePlaceId":"old-id","osmType":null,"osmId":null,"source":"LEGACY"}],
          "visits":[{"id":"visit","placeId":"place","journeyId":"run","visitedAt":3000,"note":"Private review","rating":4}],
          "photos":[{"id":"photo","relativePath":"photos/old.jpg","journeyId":"run","visitId":"visit","takenAt":3000,"latitude":41.0,"longitude":29.0,"caption":"Saved photo"}],
          "drafts":[{"id":"review","visitId":"visit","text":"Saved review","rating":4,"photoIds":["photo"],"markedSharedAt":null}],
          "contributions":[{"id":"11111111-2222-4333-8444-555555555555","placeId":"place","latitude":41.0,"longitude":29.0,"observedAt":3000,"kind":"WRONG_DETAILS","text":"Entrance moved","status":"SENDING","osmType":"WAY","osmId":123,"remoteNoteId":null,"remoteStatus":null,"submittedAt":4000,"submittedBy":77,"error":null}],
          "healthSamples":[{"journeyId":"run","sourceId":"source","originPackage":"com.sec.android.app.shealth","deviceType":1,"deviceManufacturer":"Samsung","deviceModel":"Watch8 Classic","metric":"HEART_RATE_BPM","startAt":2000,"endAt":2000,"value":90.0}],
          "mapEdits":[],
          "watchHealthSessions":[{"id":"capture","journeyId":"run","watchId":"watch","deviceName":"Watch8 Classic","createdAt":1500}],
          "watchHealthSamples":[{"sessionId":"capture","sequence":1,"journeyId":"run","metric":"HEART_RATE_BPM","startAt":3000,"endAt":3000,"value":84.0}]
        }
    """)

    fun expected() = DiarySnapshot(
        journeys = listOf(Journey(id = "run", title = "Saved run", transport = Transport.RUN,
            startedAt = 1000, endedAt = 5000, note = "Private route", stepCount = 42)),
        points = listOf(TrackPoint("point", "run", 41.0, 29.0, 2000, 5f, 2f, 10.0, true)),
        places = listOf(Place("place", "Old place", 41.0, 29.0, "old-id")),
        visits = listOf(Visit("visit", "place", "run", 3000, "Private review", 4)),
        photos = listOf(Photo("photo", "photos/old.jpg", "run", "visit", 3000, 41.0, 29.0, "Saved photo")),
        drafts = listOf(ShareDraft("review", "visit", "Saved review", 4, listOf("photo"))),
        contributions = listOf(ContributionDraft(id = "11111111-2222-4333-8444-555555555555", placeId = "place", latitude = 41.0,
            longitude = 29.0, observedAt = 3000, kind = ContributionKind.WRONG_DETAILS, text = "Entrance moved",
            status = ContributionStatus.UNKNOWN, osmType = OsmType.WAY, osmId = 123, submittedAt = 4000, submittedBy = 77)),
        healthSamples = listOf(ImportedHealthSample("source", HealthRules.SAMSUNG_HEALTH_PACKAGE, 1,
            "Samsung", "Watch8 Classic", HealthMetric.HEART_RATE_BPM, 2000, 2000, 90.0).forJourney("run")),
        watchHealthSessions = listOf(WatchHealthSession("capture", "run", "watch", "Watch8 Classic", 1500, acceptsUploads = false)),
        watchHealthSamples = listOf(WatchHealthSample("capture", 1, "run", HealthMetric.HEART_RATE_BPM, 3000, 3000, 84.0)),
    )
}
